name: urbanity
channels:
  - conda-forge
  - defaults
dependencies:
  - anyio=3.6.1=pyhd8ed1ab_1
  - appnope=0.1.3=pyhd8ed1ab_0
  - argon2-cffi=21.3.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py310hf8d0d8f_2
  - arrow=1.2.3=pyhd8ed1ab_0
  - asttokens=2.0.8=pyhd8ed1ab_0
  - attrs=22.1.0=pyh71513ae_1
  - babel=2.10.3=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - beautifulsoup4=4.11.1=pyha770c72_0
  - binaryornot=0.4.4=py_1
  - bleach=5.0.1=pyhd8ed1ab_0
  - blosc=1.21.1=hd414afc_3
  - boost-cpp=1.78.0=h1cb353e_1
  - branca=0.5.0=pyhd8ed1ab_0
  - brotli=1.0.9=h1c322ee_7
  - brotli-bin=1.0.9=h1c322ee_7
  - brotlipy=0.7.0=py310hf8d0d8f_1004
  - bzip2=1.0.8=h3422bc3_4
  - c-ares=1.18.1=h3422bc3_0
  - ca-certificates=2022.9.14=h4653dfc_0
  - cachecontrol=0.12.11=pyhd8ed1ab_0
  - cachy=0.3.0=py_0
  - cairo=1.16.0=h73a0509_1013
  - certifi=2022.9.14=pyhd8ed1ab_0
  - cffi=1.15.1=py310he00a5c5_0
  - cfitsio=4.1.0=hd4f5c17_0
  - chardet=5.0.0=py310hbe9552e_0
  - charset-normalizer=2.1.1=pyhd8ed1ab_0
  - cleo=0.8.1=pyhd8ed1ab_2
  - click=8.1.3=py310hbe9552e_0
  - click-plugins=1.1.1=py_0
  - cligj=0.7.2=pyhd8ed1ab_1
  - clikit=0.6.2=pyh9f0ad1d_0
  - contourpy=1.0.5=py310h2887b22_0
  - cookiecutter=2.1.1=pyh6c4a22f_0
  - crashtest=0.3.1=pyhd8ed1ab_0
  - cryptography=37.0.4=py310h94bb23d_0
  - curl=7.83.1=h2fcd78c_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - cykhash=2.0.0=py310h1105856_1
  - cython=0.29.32=py310hb07a4bc_0
  - debugpy=1.6.3=py310hc6dc59f_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - distlib=0.3.5=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - executing=1.0.0=pyhd8ed1ab_0
  - expat=2.4.8=h6b3803e_0
  - filelock=3.8.0=pyhd8ed1ab_0
  - fiona=1.8.21=py310hc2d5e47_2
  - flit-core=3.7.1=pyhd8ed1ab_0
  - folium=0.12.1.post1=pyhd8ed1ab_1
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.0=h82840c6_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.37.2=py310h8e9501a_0
  - freetype=2.12.1=hd633e50_0
  - freexl=1.0.6=h1a8c8d9_1
  - future=0.18.2=py310hbe9552e_5
  - gdal=3.5.2=py310hc67b115_0
  - geopandas=0.11.1=pyhd8ed1ab_0
  - geopandas-base=0.11.1=pyha770c72_0
  - geos=3.11.0=h9a09cb3_0
  - geotiff=1.7.1=hc898e3f_3
  - gettext=0.19.8.1=h049c9fb_1008
  - ghp-import=2.1.0=pyhd8ed1ab_0
  - giflib=5.2.1=h27ca646_2
  - hdf4=4.2.15=hc683e77_4
  - hdf5=1.12.2=nompi_h8968d4b_100
  - html5lib=1.1=pyh9f0ad1d_0
  - icu=70.1=h6b3803e_0
  - idna=3.3=pyhd8ed1ab_0
  - importlib-metadata=4.11.4=py310hbe9552e_0
  - importlib_metadata=4.11.4=hd8ed1ab_0
  - importlib_resources=5.9.0=pyhd8ed1ab_0
  - ipykernel=6.15.3=pyh736e0ef_0
  - ipyleaflet=0.17.1=pyhd8ed1ab_0
  - ipython=8.5.0=pyhd1c38e8_1
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=8.0.2=pyhd8ed1ab_1
  - jaraco.classes=3.2.2=pyhd8ed1ab_0
  - jedi=0.18.1=pyhd8ed1ab_2
  - jinja2=3.1.2=pyhd8ed1ab_1
  - jinja2-time=0.2.0=pyhd8ed1ab_3
  - joblib=1.2.0=pyhd8ed1ab_0
  - jpeg=9e=he4db4b2_2
  - json-c=0.16=hc449e50_0
  - json5=0.9.5=pyh9f0ad1d_0
  - jsonschema=4.16.0=pyhd8ed1ab_0
  - jupyter_client=7.3.5=pyhd8ed1ab_0
  - jupyter_core=4.11.1=py310hbe9552e_0
  - jupyter_server=1.18.1=pyhd8ed1ab_0
  - jupyterlab=3.4.7=pyhd8ed1ab_0
  - jupyterlab_pygments=0.2.2=pyhd8ed1ab_0
  - jupyterlab_server=2.15.1=pyhd8ed1ab_0
  - jupyterlab_widgets=3.0.3=pyhd8ed1ab_0
  - kealib=1.4.15=h02ce806_1
  - keplergl=0.3.2=pyhd8ed1ab_0
  - keyring=23.9.3=py310hbe9552e_0
  - kiwisolver=1.4.4=py310hd23d0e8_0
  - krb5=1.19.3=hf9b2bbe_0
  - lcms2=2.12=had6a04f_0
  - lerc=4.0.0=h9a09cb3_0
  - libblas=3.9.0=16_osxarm64_openblas
  - libbrotlicommon=1.0.9=h1c322ee_7
  - libbrotlidec=1.0.9=h1c322ee_7
  - libbrotlienc=1.0.9=h1c322ee_7
  - libcblas=3.9.0=16_osxarm64_openblas
  - libcurl=7.83.1=h2fcd78c_0
  - libcxx=14.0.6=h2692d47_0
  - libdap4=3.20.6=h8510809_2
  - libdeflate=1.14=h1a8c8d9_0
  - libedit=3.1.20191231=hc8eb9b7_2
  - libev=4.33=h642e427_1
  - libffi=3.4.2=h3422bc3_5
  - libgdal=3.5.2=he1a18a7_0
  - libgfortran=5.0.0=11_3_0_hd922786_25
  - libgfortran5=11.3.0=hdaf2cc0_25
  - libglib=2.72.1=ha1047ec_0
  - libiconv=1.16=h642e427_0
  - libkml=1.3.0=h41464e4_1015
  - liblapack=3.9.0=16_osxarm64_openblas
  - libnetcdf=4.8.1=nompi_h996a5af_104
  - libnghttp2=1.47.0=h232270b_1
  - libopenblas=0.3.21=openmp_hc731615_3
  - libpng=1.6.38=h76d750c_0
  - libpq=14.5=hb2ab832_0
  - libprotobuf=3.21.5=hb5ab8b9_3
  - librttopo=1.1.0=h275bb25_11
  - libsodium=1.0.18=h27ca646_1
  - libspatialindex=1.9.3=hbdafb3b_4
  - libspatialite=5.0.1=h47b1232_18
  - libsqlite=3.39.3=h76d750c_0
  - libssh2=1.10.0=hb80f160_3
  - libtiff=4.4.0=hfa0b094_4
  - libuv=1.44.2=he4db4b2_0
  - libwebp-base=1.2.4=h57fd34a_0
  - libxcb=1.13=h9b22ae9_1004
  - libxml2=2.9.14=h9d8dfc2_4
  - libxslt=1.1.35=ha8fb468_0
  - libzip=1.9.2=h96606af_1
  - libzlib=1.2.12=h03a7124_3
  - llvm-openmp=14.0.4=hd125106_0
  - lockfile=0.12.2=py_1
  - lxml=4.9.1=py310h02f21da_0
  - lz4-c=1.9.3=hbdafb3b_1
  - mapbox-vector-tile=1.2.0=py_0
  - mapclassify=2.4.3=pyhd8ed1ab_0
  - markdown=3.4.1=pyhd8ed1ab_0
  - markupsafe=2.1.1=py310hf8d0d8f_1
  - matplotlib-base=3.6.0=py310h78c5c2f_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mercantile=1.2.1=pyhd8ed1ab_0
  - mergedeep=1.3.4=pyhd8ed1ab_0
  - mistune=2.0.4=pyhd8ed1ab_0
  - mkdocs=1.3.0=pyhd8ed1ab_0
  - more-itertools=8.14.0=pyhd8ed1ab_0
  - msgpack-python=1.0.4=py310hd23d0e8_0
  - munch=2.5.0=py_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - nb_conda_kernels=2.3.1=py310hbe9552e_1
  - nbclassic=0.4.3=pyhd8ed1ab_0
  - nbclient=0.6.8=pyhd8ed1ab_0
  - nbconvert=7.0.0=pyhd8ed1ab_0
  - nbconvert-core=7.0.0=pyhd8ed1ab_0
  - nbconvert-pandoc=7.0.0=pyhd8ed1ab_0
  - nbformat=5.5.0=pyhd8ed1ab_0
  - ncurses=6.3=h07bb92c_1
  - nest-asyncio=1.5.5=pyhd8ed1ab_0
  - networkx=2.8.6=pyhd8ed1ab_0
  - nodejs=18.9.0=haa6f3e8_0
  - notebook=6.4.12=pyha770c72_0
  - notebook-shim=0.1.0=pyhd8ed1ab_0
  - nspr=4.32=hbdafb3b_1
  - nss=3.78=h1483a63_0
  - numpy=1.23.3=py310h5d7c261_0
  - openjpeg=2.5.0=h5d4e404_1
  - openssl=1.1.1q=ha287fd2_0
  - packaging=20.9=pyh44b312d_0
  - pandas=1.4.4=py310h2b830bf_0
  - pandoc=2.12=hca03da5_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pastel=0.2.1=pyhd8ed1ab_0
  - pcre=8.45=hbdafb3b_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pillow=9.2.0=py310h173adc3_2
  - pip=22.2.2=pyhd8ed1ab_0
  - pixman=0.40.0=h27ca646_0
  - pkginfo=1.8.3=pyhd8ed1ab_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_0
  - platformdirs=2.5.2=pyhd8ed1ab_1
  - poetry=1.1.15=py310hbe9552e_0
  - poetry-core=1.0.8=py310hbe9552e_1
  - poppler=22.04.0=h4f9e0c6_3
  - poppler-data=0.4.11=hd8ed1ab_0
  - postgresql=14.5=hb0ca4ee_0
  - proj=9.0.1=h4c79c2b_1
  - prometheus_client=0.14.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.31=pyha770c72_0
  - protobuf=4.21.5=py310h0f1eb42_1
  - psutil=5.9.2=py310h8e9501a_0
  - pthread-stubs=0.4=h27ca646_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pyclipper=1.3.0.post3=py310hb07a4bc_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pygeos=0.13=py310hc253cc3_0
  - pygments=2.13.0=pyhd8ed1ab_0
  - pylev=1.4.0=pyhd8ed1ab_0
  - pyopenssl=22.0.0=pyhd8ed1ab_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pyproj=3.4.0=py310h7275060_0
  - pyrobuf=0.9.3=py310h1105856_4
  - pyrosm=0.6.1=py310h1105856_1
  - pyrsistent=0.18.1=py310hf8d0d8f_1
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.10.6=hbce4517_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-fastjsonschema=2.16.1=pyhd8ed1ab_0
  - python-rapidjson=1.6=py310h1105856_0
  - python-slugify=6.1.2=pyhd8ed1ab_0
  - python_abi=3.10=2_cp310
  - pytz=2022.2.1=pyhd8ed1ab_0
  - pyyaml=6.0=py310hf8d0d8f_4
  - pyyaml-env-tag=0.1=pyhd8ed1ab_0
  - pyzmq=24.0.0=py310hc407298_0
  - readline=8.1.2=h46ed386_0
  - requests=2.28.1=pyhd8ed1ab_1
  - requests-toolbelt=0.9.1=py_0
  - rtree=1.0.0=py310ha3239f5_1
  - scikit-learn=1.1.2=py310h3d7afdd_0
  - scipy=1.9.1=py310ha0d8a01_0
  - send2trash=1.8.0=pyhd8ed1ab_0
  - setuptools=65.3.0=pyhd8ed1ab_1
  - shapely=1.8.4=py310h2f36b14_0
  - shellingham=1.5.0=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.1.9=h39c3846_1
  - sniffio=1.3.0=pyhd8ed1ab_0
  - soupsieve=2.3.2.post1=pyhd8ed1ab_0
  - sqlite=3.39.3=h2229b38_0
  - stack_data=0.5.0=pyhd8ed1ab_0
  - terminado=0.15.0=py310hbe9552e_0
  - text-unidecode=1.3=py_0
  - threadpoolctl=3.1.0=pyh8a188c0_0
  - tiledb=2.11.2=hc7ac4c9_0
  - tinycss2=1.1.1=pyhd8ed1ab_0
  - tk=8.6.12=he1e0b03_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - tomlkit=0.11.4=pyha770c72_0
  - tornado=6.2=py310h02f21da_0
  - traitlets=5.4.0=pyhd8ed1ab_0
  - traittypes=0.2.1=pyh9f0ad1d_2
  - typing=3.10.0.0=pyhd8ed1ab_0
  - typing_extensions=4.3.0=pyha770c72_0
  - tzcode=2022c=h57fd34a_0
  - tzdata=2022c=h191b570_0
  - unicodedata2=14.0.0=py310hf8d0d8f_1
  - unidecode=1.3.4=pyhd8ed1ab_0
  - urllib3=1.26.11=pyhd8ed1ab_0
  - virtualenv=20.16.5=py310hbe9552e_0
  - watchdog=2.1.9=py310h02f21da_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - websocket-client=1.4.1=pyhd8ed1ab_0
  - wheel=0.37.1=pyhd8ed1ab_0
  - widgetsnbextension=4.0.3=pyhd8ed1ab_0
  - xerces-c=3.2.3=h1b0b642_5
  - xorg-libxau=1.0.9=h27ca646_0
  - xorg-libxdmcp=1.1.3=h27ca646_0
  - xyzservices=2022.6.0=pyhd8ed1ab_0
  - xz=5.2.6=h57fd34a_0
  - yaml=0.2.5=h3422bc3_2
  - zeromq=4.3.4=hbdafb3b_1
  - zipp=3.8.1=pyhd8ed1ab_0
  - zlib=1.2.12=h03a7124_3
  - zstd=1.5.2=h8128057_4
  - pip:
    - urbanity==0.2.1
prefix: /Users/winston/miniconda3/envs/urbanity
