[tool.poetry]
name = "urbanity"
version = "0.3.0"
description = ""
authors = ["winstonyym <winstonyym@u.nus.edu>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
vt2geojson = "^0.2.1"
networkx = "2.8.6"
geopandas = "0.11.1"
numpy = "1.23.3"
pyrosm = "0.6.1"
Shapely = "1.8.4"
rasterio = "1.3.2"
ipyleaflet = "0.17.1"

[tool.poetry.dev-dependencies]
pytest = "^7.1.3"
pytest-cov = "^4.0.0"
jupyter = "^1.0.0"
myst-nb = "^0.17.1"
sphinx-autoapi = "^2.0.0"
sphinx-rtd-theme = "^1.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
